name: Release
run-name: Release

on:
  workflow_dispatch:

permissions:
  contents: read # for checkout

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: >
      ${{
        github.repository_owner == 'mumincelal' &&
        github.actor == 'mumincelal'
      }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create release
      issues: write # to post issue comments
      pull-requests: write # to create pull request
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
